import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Activity from './models/Activity';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/nss-db';

const events = [
  {
    title: 'Plantation Drive',
    category: 'Plantation Drive',
    date: new Date('2022-08-04'),
    venue: 'Faculty House',
    description: 'The NSS unit organized a Plantation Drive around the Faculty House to promote environmental awareness and sustainability. Volunteers actively participated in planting various saplings, including neem, peepal, and flowering plants, within the surroundings of faculty residence . The activity aimed to encourage eco-friendly practices and highlight the importance of greenery in maintaining ecological balance. All necessary arrangements, such as tools and saplings, were managed efficiently by the team. Faculty members also appreciated the efforts of NSS volunteers. The drive not only enhanced the green cover of the campus but also instilled a sense of responsibility among students towards environmental conservation.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Event of Home Minister (Stationary Kit Donation)',
    category: 'Social Service',
    date: new Date('2022-08-06'),
    venue: 'Bhopal',
    description: 'The NSS unit organized a Stationary Kit Donation event initiated by the Honorable Home Minister. The movement aimed to support underprivileged and medical students by providing essential educational materials. The Home Minister personally donated stationery kits, including notebooks, pens, and pencils, inspiring others to contribute to this noble cause. NSS volunteers actively managed and coordinated the event efficiently. The initiative highlighted the importance of education and equal opportunities for all. It also encouraged a spirit of social responsibility and service among students, motivating them to contribute towards the betterment of society.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Har Ghar Tiranga',
    category: 'Awareness Drive',
    date: new Date('2022-08-10'),
    venue: 'Auditorium 1',
    description: 'On the occasion of Azadi Ka Amrit Mahotsav, the National Service Scheme (NSS) unit of VIT University organized the “Har Ghar Tiranga” program on 10th August 2022 (Wednesday). My FM joined as the radio partner for the event. Students participated with great enthusiasm and shared interesting facts about the Indian national flag. The event was hosted by My FM RJ Munish. On this occasion, all students took a pledge to hoist the national flag and respect its dignity. The event was graced by Registrar Mr. Pradyuman Yadav, DSW Dr. George Chandran, Program Officer Dr. Vinod Bhatt, and other faculty members.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Independence Day Program',
    category: 'General',
    date: new Date('2022-08-15'),
    venue: 'Main Gate and Auditorium 1',
    description: 'The NSS unit of VIT University organized a grand Independence Day Celebration on 15th August with great enthusiasm and patriotic spirit. The event began with a ceremonial parade by NSS volunteers, followed by the hoisting of the national flag. Students showcased discipline and unity through march past and cultural performances. Various activities, including patriotic songs and speeches, highlighted the significance of freedom and national pride. Faculty members and university officials graced the occasion. The celebration aimed to instill a sense of patriotism, responsibility, and unity among students, making the event memorable and inspiring for all participants.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'NSS Week Celebration',
    category: 'General',
    date: new Date('2022-09-19'),
    venue: 'VIT Bhopal University',
    description: 'The NSS Unit of VIT Bhopal University celebrated NSS Week with great enthusiasm to mark NSS Day. The week included various activities such as an awareness rally on cleanliness and health schemes in an adopted village, promoting community engagement. Competitions like poster making and essay writing on “India in Next 10 Years” encouraged creativity among volunteers. A blood donation camp was also organized in collaboration with AIIMS Bhopal, where students and faculty actively participated. The celebration concluded with a debate competition on media’s role in democracy, fostering critical thinking. The event highlighted teamwork, social responsibility, and the true spirit of NSS.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Blood Donation Camp',
    category: 'Blood Donation Camp',
    date: new Date('2022-12-15'),
    venue: 'Auditorium 1',
    description: 'The NSS Unit of VIT Bhopal University organized a blood donation camp on 15th December 2022 in memory of Late Smt. Rajeswari Viswanathan. The event was conducted in the presence of the Vice Chancellor, Pro Vice Chancellor, Registrar, NSS Program Officers, and faculty members. The camp began with an initial donation by Dr. Sriram R, followed by active participation from students and faculty. Around 160+ students volunteered for this noble cause. The camp was successfully organized with proper discipline and medical support. Blood collection was carried out by Chirayu Medical College & Hospital, contributing to saving lives.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Republic Day Parade and Celebrations',
    category: 'General',
    date: new Date('2023-01-26'),
    venue: 'University Main Gate',
    description: 'The NSS Unit of VIT Bhopal University celebrated Republic Day on 26th January with great pride and patriotism. The event began with the hoisting of the national flag, followed by a disciplined parade conducted by NSS volunteers. Students showcased unity and dedication through march past and saluting the national flag. Various cultural performances, patriotic songs, and speeches were organized to highlight the importance of the Constitution. Faculty members and university officials graced the occasion. The celebration aimed to instill values of unity, responsibility, and respect for the nation among students, making the event inspiring and memorable.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Nukkad Natak',
    category: 'Awareness Drive',
    date: new Date('2023-03-03'),
    venue: 'Dabla, Sehore',
    description: 'On the occasion of Women’s Day, the NSS Unit of VIT Bhopal University organized a street play (Nukkad Natak) titled “Mai Bhi Shakti” in a nearby village to promote women empowerment. NSS volunteers performed impactful acts highlighting women’s safety, girl child education, and domestic violence. The performance aimed to spread awareness about women’s rights and inspire social change. The event was followed by a rally with slogans on women empowerment. The village Sarpanch also delivered an encouraging speech. The event was successfully conducted under the guidance of Dr. Vinod Bhatt and Dr. Neetu Kalra, making it meaningful and impactful.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Blood Donation Camp',
    category: 'Blood Donation Camp',
    date: new Date('2023-05-11'),
    venue: 'Auditorium 1',
    description: 'The NSS Unit of VIT Bhopal University organized a Blood Donation Camp to promote the importance of saving lives through blood donation. The camp witnessed active participation from students and faculty members who volunteered for this noble cause. Proper medical arrangements were ensured, and all safety measures were followed during the process. A significant number of donors contributed, making the camp successful. Volunteers efficiently managed registrations and coordination. The initiative aimed to create awareness about the importance of regular blood donation and encourage social responsibility among students, reflecting the true spirit of NSS, “Not Me But You.”',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Plantation Drive',
    category: 'Plantation Drive',
    date: new Date('2023-07-20'),
    venue: 'Near Mayuri Canteen',
    description: 'The NSS Unit of VIT Bhopal University organized a Plantation Drive near the garden and hostel areas to promote environmental sustainability. NSS volunteers actively participated in planting various saplings and enhancing the green cover of the campus. The activity aimed to spread awareness about the importance of trees in maintaining ecological balance and a healthy environment. Volunteers worked together with great enthusiasm and ensured proper planting and care of saplings. The initiative encouraged students to adopt eco-friendly practices and take responsibility for nature, making the campus greener and contributing towards a sustainable future.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Nukkad Natak (Plastic Free campus)',
    category: 'Awareness Drive',
    date: new Date('2023-08-09'),
    venue: 'Kotri Primary School',
    description: 'The NSS Unit of VIT Bhopal University organized a Nukkad Natak on the theme “Plastic Free Campus” to spread awareness about the harmful effects of plastic usage. NSS volunteers performed an engaging street play highlighting issues like environmental pollution, health hazards, and the need to reduce single use plastic. The performance effectively conveyed the message of adopting eco-friendly alternatives. Students and faculty actively participated and appreciated the initiative. The event aimed to encourage responsible behavior and promote a clean and sustainable campus, reflecting the commitment of NSS volunteers towards environmental protection and social awareness.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'National Youth Parliament',
    category: 'General',
    date: new Date('2023-08-14'),
    venue: 'AB - 207',
    description: 'The NSS Unit of VIT Bhopal University organized the National Youth Parliament to promote awareness about democratic values and parliamentary procedures among students. Participants actively took part by representing various roles such as ministers, opposition members, and speakers, creating a realistic parliamentary environment. The session included discussions on important national issues, encouraging critical thinking and effective communication. Students showcased confidence, leadership, and public speaking skills throughout the event. Faculty members guided and evaluated the participants. The activity aimed to develop a sense of responsibility, leadership, and understanding of governance among youth, making it an informative and engaging experience.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Blood Donation Camp',
    category: 'Blood Donation Camp',
    date: new Date('2023-11-14'),
    venue: 'Auditorium 1',
    description: 'The NSS Unit of VIT Bhopal University organized a Blood Donation Camp to contribute towards saving lives and supporting healthcare needs. Students and faculty members actively participated in this noble initiative. The camp was conducted under proper medical supervision, ensuring safety and hygiene for all donors. NSS volunteers efficiently managed registrations and arrangements, making the event smooth and well-organized. A considerable number of blood units were collected, reflecting the enthusiasm and generosity of participants. The event successfully raised awareness about the importance of blood donation and encouraged students to become responsible and compassionate citizens.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Annual Unit NSS Camp',
    category: 'General',
    date: new Date('2024-02-08'),
    venue: 'Kachnaria',
    description: 'The NSS Unit of VIT Bhopal University organized its Annual Unit Camp 2024 in Kachnaria Village to promote community service and rural development. NSS volunteers actively participated in various activities such as cleanliness drives, awareness campaigns on health and hygiene, and interaction with villagers to understand their lifestyle and challenges. Educational sessions and social awareness programs were also conducted for children and villagers. The camp helped volunteers develop leadership, teamwork, and social responsibility. It created a positive impact on the village community and strengthened the bond between students and society, reflecting the true spirit of NSS, “Not Me But You.”',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Nukkad Natak - Women Empowerment',
    category: 'Awareness Drive',
    date: new Date('2024-03-05'),
    venue: 'Kachnaria',
    description: 'The NSS Unit of VIT Bhopal University organized a Nukkad Natak on the theme of Women Empowerment to spread awareness about gender equality and women’s rights. NSS volunteers performed an impactful street play highlighting issues such as women’s safety, education, and social equality. The performance aimed to inspire positive change and encourage respect and dignity for women in society. The event received great appreciation from the audience. It was followed by awareness messages promoting equal opportunities for women. The activity successfully instilled a sense of responsibility and sensitivity among students towards women empowerment.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Washroom Restoration',
    category: 'Social Service',
    date: new Date('2024-03-05'),
    venue: 'Kachnaria',
    description: 'The NSS Unit of VIT Bhopal University undertook a meaningful initiative by restoring the girls’ washroom at the Government Secondary School in Kachnaria Village on 5th March 2024. The renovation work was carried out during the seven-day NSS camp with the support of university management. The restored facility was inaugurated by the Registrar in the presence of faculty members, NSS Program Officers, and villagers. This initiative aimed to improve hygiene, health, and safety for girl students. It promoted awareness about sanitation and women’s dignity, creating a positive impact on the community and encouraging girl child education.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'National Youth Parliament',
    category: 'General',
    date: new Date('2024-04-16'),
    venue: 'Auditorium 1',
    description: 'The NSS Unit of VIT Bhopal University organized the National Youth Parliament on 16th April 2024 to promote political awareness among students. The event began with a lamp lighting ceremony honoring Swami Vivekananda and Maa Sharda. University officials and NSS Program Officers inaugurated the session. Students actively participated as members of ruling and opposition parties, debating on topics like media’s role, One Nation One Election, and Make in India. Two bills were passed after detailed discussions. The event enhanced students’ understanding of parliamentary procedures, leadership, and decision-making, encouraging active participation in democratic processes.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'UNGLI PE TILAK',
    category: 'Awareness Drive',
    date: new Date('2024-05-06'),
    venue: 'MULTI PURPOSE HALL (MPH)',
    description: 'The NSS Unit of VIT Bhopal University organized a Nukkad Natak titled “Ungli Par Tilak” to spread awareness about the importance of voting for the Lok Sabha Elections 2024. The street play highlighted the crucial role of every citizen in shaping the nation through active participation in the electoral process. Volunteers effectively conveyed the message of responsible voting and making informed decisions. The performance also emphasized the upcoming election phases and encouraged people to vote. The initiative successfully promoted democratic values and inspired citizens to actively contribute towards strengthening the democracy of the nation.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Water and Food for Birds',
    category: 'Social Service',
    date: new Date('2024-05-08'),
    venue: 'VIT Bhopal University Campus premises',
    description: 'The NSS Unit of VIT Bhopal University organized a Bird Feeder Installation Drive on 8th May 2024 to support campus biodiversity. Volunteers installed 15 bird feeders and water pots across the campus to provide food and water for birds, especially during summer. The initiative aimed to create a safe and welcoming environment for avian species while promoting environmental awareness. NSS volunteers committed to regularly refilling and maintaining the feeders. The activity encouraged responsibility, sustainability, and compassion towards nature. It was a successful initiative that enhanced the campus ecosystem and reflected the NSS spirit of environmental stewardship.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'EYE CHECK UP CAMP',
    category: 'Health Camp',
    date: new Date('2024-08-05'),
    venue: 'LC-201',
    description: 'The NSS Unit of VIT Bhopal University organized a Free Eye Checkup Camp on 5th August 2024 to promote eye health awareness. The camp witnessed an overwhelming response with over 1100 registrations from students, faculty, and staff. The event was conducted under the guidance of Dr. Atul Upadhyay and supported by NSS Program Officers. Various tests including vision, retina check, and eye correction were conducted. NSS volunteers ensured smooth coordination throughout the event. The initiative helped participants understand the importance of regular eye checkups and encouraged preventive care, making it a highly successful and impactful program.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'NSS Mega Tree Plantation Drive',
    category: 'Plantation Drive',
    date: new Date('2024-08-09'),
    venue: 'Ujarkheda, Daboti, Sehore',
    description: 'The NSS Unit of VIT Bhopal University organized a Mega Tree Plantation Drive on 9th August 2024 with great enthusiasm. Around 1000 volunteers actively participated and planted nearly 10,000 saplings across the campus. The event aimed to promote environmental sustainability and create a greener future. Under the guidance of NSS Program Officers, volunteers worked with dedication and teamwork. The presence of university dignitaries motivated participants further. The drive fostered unity, responsibility, and awareness about environmental conservation. It was a highly successful initiative that strengthened the bond between students and nature, reflecting the true spirit of NSS and collective action.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Blood Donation Camp',
    category: 'Blood Donation Camp',
    date: new Date('2024-08-14'),
    venue: 'Auditorium 1 and 2',
    description: 'The NSS Unit of VIT Bhopal University organized a Blood Donation Camp with great enthusiasm and participation. Volunteers gathered early to manage arrangements, including setup of equipment and registration desks, ensuring smooth execution. The event began with a lamp lighting ceremony, followed by systematic blood donation under proper medical supervision. Around 400 donors actively participated, making the camp highly successful. The initiative created awareness about the importance of blood donation and inspired many to contribute in the future. The event promoted empathy, social responsibility, and the spirit of helping others, leaving a meaningful impact on both donors and organizers.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'NSS Week (Swaccha Hi Seva)',
    category: 'Awareness Drive',
    date: new Date('2024-09-22'),
    venue: 'VIT Bhopal University Campus',
    description: 'The NSS Unit of VIT Bhopal University organized the Swachhta Hi Seva campaign from 23rd September to 2nd October 2024 to promote cleanliness and Gandhian values. The campaign included activities like poster making, cleanliness rallies, debate and essay competitions, tree plantation, nukkad natak, upcycling workshop, and film-making competition. Volunteers actively participated and took a cleanliness pledge to dedicate time for maintaining hygiene and spreading awareness. The initiative emphasized “Not Me But You” by encouraging community service and responsibility. The campaign successfully instilled awareness about cleanliness and inspired students to contribute towards building a clean and developed India.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'FIT India Rally',
    category: 'Health Camp',
    date: new Date('2024-12-05'),
    venue: 'VIT Bhopal University Campus',
    description: 'The NSS Unit of VIT Bhopal University organized a FIT India Rally to promote health, fitness, and an active lifestyle among students. NSS volunteers enthusiastically participated in the rally, spreading awareness about the importance of physical fitness and well-being. Participants carried banners and raised slogans encouraging daily exercise and healthy habits. The rally covered key areas of the campus, engaging students and faculty members. The initiative aimed to inspire individuals to adopt a fit and disciplined lifestyle. The event successfully highlighted the importance of fitness in daily life and motivated students to stay active and healthy.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Blood Donation Camp',
    category: 'Blood Donation Camp',
    date: new Date('2024-12-12'),
    venue: 'Auditorium 1 and 2',
    description: 'The NSS Unit of VIT Bhopal University organized a Blood Donation Camp on 12th December 2024 to support healthcare needs and promote voluntary blood donation. The camp was conducted at the Auditorium in collaboration with Hamidi Hospital, ensuring proper medical supervision and safety. Over 350 donors, including students, faculty, and staff, actively participated in this noble cause. NSS volunteers efficiently managed registrations and awareness activities. The initiative highlighted the importance of blood donation and collective responsibility towards society. The event was a great success, contributing to saving lives and strengthening the spirit of service among participants.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'NSS Unit Camp 2025',
    category: 'General',
    date: new Date('2025-01-24'),
    venue: 'Jafrabad, Sehore',
    description: 'The NSS Unit of VIT Bhopal University organized the NSS Unit Camp 2025 with the aim of promoting community service and rural development. Volunteers actively participated in various activities such as cleanliness drives, health and hygiene awareness campaigns, tree plantation, and interaction with villagers. Educational sessions were conducted to spread awareness about social issues and government schemes. The camp helped volunteers develop leadership, teamwork, and a sense of social responsibility. It created a positive impact on the local community while providing students with practical exposure to real-life challenges, reflecting the true spirit of NSS, “Not Me But You.”',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'National Youth Parliament 2025',
    category: 'General',
    date: new Date('2025-04-03'),
    venue: 'Auditorium 1',
    description: 'The NSS Unit of VIT Bhopal University organized the Viksit Bharat National Youth Parliament 2025 to promote political awareness and leadership among students. The event simulated real parliamentary procedures, where participants took roles as MPs and ministers. Activities like Zero Hour, Question Hour, and bill discussions enhanced understanding of governance. Over 200 registrations were received, with selected participants showcasing excellent communication and critical thinking skills. The event aimed to develop decision-making, public speaking, and respect for diverse opinions. It was a highly engaging and educational experience, inspiring students to become responsible citizens and future leaders.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Water and Food for Birds 2025',
    category: 'Social Service',
    date: new Date('2025-04-15'),
    venue: 'VIT Bhopal Campus Premises',
    description: 'The NSS Unit of VIT Bhopal University organized a “Water and Food for Birds” initiative to support birdlife during the summer season. Volunteers installed 35 clay pots at various locations across the campus to provide water and food for birds. The initiative aimed to protect birds from extreme heat and resource scarcity. NSS volunteers ensured regular maintenance and refilling of the pots. The activity promoted compassion, environmental awareness, and biodiversity conservation. It also enhanced teamwork and responsibility among students. The initiative was a meaningful step towards protecting wildlife and creating a sustainable and eco-friendly campus environment.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Orientation Program 2024 Batch',
    category: 'General',
    date: new Date('2025-07-17'),
    venue: 'LC-002',
    description: 'The NSS Unit of VIT Bhopal University organized the NSS Orientation Program on 17th July 2024 for newly enrolled volunteers. The session introduced students to the vision, values, and functioning of NSS along with its motto “Not Me, But You.” Volunteers were briefed about various activities, camps, and responsibilities throughout the year. The program highlighted the importance of teamwork, discipline, and social service. Interactive sessions motivated students to actively participate in NSS initiatives. The orientation successfully provided clarity about roles and opportunities, encouraging students to develop leadership skills and contribute towards community welfare.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Mega Tree Plantation Drive 2025',
    category: 'Plantation Drive',
    date: new Date('2025-07-24'),
    venue: 'VIT Bhopal University Campus',
    description: 'The NSS Unit of VIT Bhopal University organized the Mega Plantation Drive 2025 to promote environmental sustainability and awareness. Around 500 volunteers actively participated and planted over 3,000 saplings across the campus. The event encouraged teamwork, leadership, and responsibility among students as they worked in coordinated teams. Volunteers gained awareness about afforestation and ecological balance. The initiative emphasized discipline, community participation, and environmental care. It was a successful effort towards creating a greener campus and fostering a sense of social responsibility among students, reflecting the core values of NSS and commitment towards a sustainable future.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Free Eye and Dental Checkup Camp',
    category: 'Health Camp',
    date: new Date('2025-07-31'),
    venue: 'Mini Auditorium AB1, VIT Bhopal University',
    description: 'The NSS Unit of VIT Bhopal University organized a Free Health Checkup Camp 2025 to promote preventive healthcare and well-being. The camp offered dental and eye checkups for students, faculty, and staff. Over 1500 checkups were conducted in a single day, reflecting active participation. Advanced facilities like a mobile dental unit, diagnostic tools, oral cancer detection devices, and dental lasers were utilized. Complimentary treatment coupons were also provided to attendees. NSS volunteers ensured smooth coordination throughout the event. The initiative raised awareness about early diagnosis and healthy practices, making it a highly impactful and successful healthcare program.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'VIBGYOR',
    category: 'General',
    date: new Date('2025-09-19'),
    venue: 'Auditorium 1, VIT Bhopal University',
    description: 'The NSS Unit of VIT Bhopal University organized VIBGYOR 2025, its first cultural event, to celebrate the rich diversity and heritage of India. The event showcased performances from different states, creating a vibrant and inclusive atmosphere. NSS also highlighted its activities such as health camps, youth parliament, and social awareness drives. The event aimed to engage freshers and encourage participation in community service. It promoted teamwork, leadership, and organizational skills among students. VIBGYOR 2025 successfully combined culture with social responsibility, inspiring students to connect with the NSS motto, “Not Me But You.”',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'ORIENTATION PROGRAM 2025',
    category: 'General',
    date: new Date('2025-11-07'),
    venue: 'Auditorium 1, VIT Bhopal University',
    description: 'The NSS Unit of VIT Bhopal University organized the NSS Orientation Program on 7th November 2025 for newly enrolled volunteers. The session introduced students to the vision, values, and functioning of NSS along with its motto “Not Me, But You.” Volunteers were given an overview of various activities, camps, and responsibilities throughout the year. The program emphasized teamwork, discipline, and community service. Interactive sessions motivated students to actively participate in NSS initiatives. The orientation successfully prepared volunteers by enhancing their understanding of leadership, social responsibility, and the importance of contributing towards society.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Annual NSS Camp 2026',
    category: 'General',
    date: new Date('2026-02-02'),
    venue: 'Bor Kheda, Sehore',
    description: 'The NSS Unit of VIT Bhopal University organized a seven-day Annual Special Camp 2026 from 2nd to 8th February at Borkheda Village, Ashta. Volunteers actively participated in activities such as cleanliness drives, awareness rallies, medical camp, cloth and educational material donation, and plantation drives. Nukkad nataks on social issues like women empowerment and digital awareness were performed. Intellectual sessions on cyber security, AI, and human rights enriched knowledge. Cultural programs and community interaction strengthened bonding with villagers. The camp enhanced leadership, teamwork, and social responsibility among volunteers, creating a positive impact and reflecting the true spirit of NSS, “Not Me But You.”',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  },
  {
    title: 'Blood Donation Camp',
    category: 'Blood Donation Camp',
    date: new Date('2026-03-05'),
    venue: 'Auditorium 1 and 2, VIT Bhopal University',
    description: 'The NSS Unit of VIT Bhopal University organized a Blood Donation Camp on 5th March 2026 to promote voluntary blood donation and social responsibility. The event was conducted at the Auditorium and Mini Auditorium on the occasion of the birthday of Hon’ble Mrs. Kadhambari Viswanathan. The medical team from Hamidia Medical College supervised the process, ensuring safety and hygiene. The camp began with a lamp lighting ceremony in the presence of university dignitaries. Over 400 donors actively participated, making it a great success. The initiative encouraged empathy, community service, and awareness about the importance of saving lives.',
    isRegistrationOpen: false,
    hoursAllocated: 5,
  }
];

mongoose.connect(MONGODB_URI)
  .then(async () => {
    console.log('Connected to DB. Seeding activities...');
    // Only delete mock data or clear if needed. Let's just clear all activities for a fresh start.
    await Activity.deleteMany({});
    
    await Activity.insertMany(events);
    console.log('Activities seeded successfully!');
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });
